---

- name: fetch golang binaries
  shell:
    curl -O {{ golang.src_url }}
    creates={{ golang.tar }}

- name: install golang
  sudo: true
  shell:
    tar -C /usr/local -zxf {{ golang.tar }}
    creates=/usr/local/go/bin/

- name: activate golang
  lineinfile:
    dest=~/.bashrc
    line="export PATH=$PATH:/usr/local/go/bin; export GOPATH=~/.go"
    state=present
    backup=yes
    insertafter=EOF
