---

- name: add apt key for node.js launchpad repo
  sudo: true
  shell:
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys {{ nodejs_apt_key }}

- name: add apt repo for node.js
  sudo: true
  apt_repository: repo='{{ nodejs_apt_repo }}' state=present

- name: add apt sid repo
  sudo: true
  apt_repository: repo='{{ sid_apt_repo }}' state=present

- name: install nodejs (with deps) package
  sudo: true
  apt: pkg={{ item }} state=installed
  with_items:
    - libc6-dev
    - nodejs

- name: install npm packages
  sudo: true
  npm: name={{ item }} global=yes
  with_items:
    - grunt-cli
    - lodash
