---

- name: fetch node.js sources
  shell:
    curl -O {{ nodejs_src_url }}
    creates={{ nodejs_tar }}

- name: install node.js
  sudo: true
  shell:
    tar -zxf {{ nodejs_tar }}
    && cd {{ nodejs_src_folder }}
    && ./configure && make && make install
    creates=/usr/local/bin/node

- name: install npm packages
  sudo: true
  npm: name={{ item }} global=yes
  with_items:
    - grunt-cli
    - lodash
